version: "3"
services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest
    ports:
      - 7300:61208
    environment:
      - TZ=UTC+1
      - GLANCES_OPT=-w
    pid: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro