- hosts: debian

  become: yes
  tasks:
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send ntfy message
      ntfy:
        url: "http://laydia.teqcloud.net"
        msg: "Reboot required on {{ inventory_hostname }} to complete the update"
        topic: "updates"
        attrs:
          tags: [ warning ]
          priority: 3
      when: reboot_required.stat.exists