log:
  level: INFO

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  cloudflare:
    acme:
      email: "${CF_API_EMAIL}"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare
