services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: laydia.teqcloud.net:7000
    ports:
      - 7000:3000
    volumes:
      - /data/docker-compose/homepage:/app/config
    restart: unless-stopped