- hosts: debian

  become: yes
  tasks:
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
      register: updated

    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send ntfy message [reboot required]
      ntfy:
        url: "http://laydia.teqcloud.net"
        msg: "Reboot required on {{ inventory_hostname }} to complete the update"
        topic: "updates"
        attrs:
          tags: [ warning ]
          priority: 3
          actions:
            - action: view
              label: "Schedule Reboot"
              url: "https://vc.teqcloud.net/ui/"
      when: reboot_required.stat.exists

    - name: Send ntfy message [succes]
      ntfy:
        url: "http://laydia.teqcloud.net"
        msg: "Update {{ inventory_hostname }} is completed succesfully"
        topic: "updates"
        attrs:
          tags: [ warning ]
          priority: 3
      when: updated.stat.exist and not reboot_required.stat.exists